### ISSUE TITLE
Dividir string de la lectura del archivo.ar

### ISSUE THREAD

**Issue by xooseph** [adayair25/Arithmo#2]
Cuando se lee el archivo y se almacena en `content`, queda un string con todo el código, es necesario dividir para que se manden los tokens necesarios al parser para bloque de código.
<img width="260" alt="Captura de pantalla 2024-07-18 021529" src="https://github.com/user-attachments/assets/7cdf8254-a373-47bf-a145-03f1645ae025">

**Comment by MarioYellowy** [comment]
Checando
