### ISSUE TITLE
Can't create variable one line

### ISSUE THREAD

**Issue by MarioYellowy** [adayair25/Arithmo#4]
Dentro del archivo .ar no se puede crear variables que compartan el mismo tipo dentro de una linea, ejemplo:
![image](https://github.com/user-attachments/assets/11ea0d69-2302-4ae7-83dc-7ef7189f4814)
El resultado es este:
![image](https://github.com/user-attachments/assets/8e02728d-b087-46cd-b878-03150ca110bd)

**Comment by adayair25** [comment]
Se puede arreglar y queda pendiente, por que ahorita esta un poco complicado corregirlo, cuando terminemos el parse, se podra arreglar

**Comment by adayair25** [comment]
Listo mario, ya se soluciono
![image](https://github.com/user-attachments/assets/d6c463f5-3512-4fc5-bf86-97d8ce9494a7)
